# Generated by Django 4.1.5 on 2023-01-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='push',
        ),
    ]
