# Generated by Django 4.1.5 on 2023-01-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0003_remove_users_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aed',
            field=models.IntegerField(help_text='aed', max_length=10, null=True, verbose_name='USD'),
        ),
        migrations.AlterField(
            model_name='users',
            name='eur',
            field=models.IntegerField(help_text='aed', max_length=10, null=True, verbose_name='USD'),
        ),
        migrations.AlterField(
            model_name='users',
            name='usd',
            field=models.IntegerField(help_text='usd', max_length=10, null=True, verbose_name='USD'),
        ),
    ]
