# Generated by Django 4.1.5 on 2023-01-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0005_curs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='aed',
            field=models.FloatField(help_text='aed', max_length=10, null=18.1, verbose_name='USD'),
        ),
        migrations.AlterField(
            model_name='curs',
            name='eur',
            field=models.IntegerField(help_text='aed', max_length=10, null=74.1, verbose_name='USD'),
        ),
        migrations.AlterField(
            model_name='curs',
            name='usd',
            field=models.IntegerField(help_text='usd', max_length=10, null=68.1, verbose_name='USD'),
        ),
    ]
