# Generated by Django 4.1.5 on 2023-01-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='user_id', max_length=500, null=True, verbose_name='user_id')),
                ('usd', models.IntegerField(help_text='usd', max_length=10, null=None, verbose_name='usd')),
                ('aed', models.IntegerField(help_text='aed', max_length=10, null=None, verbose_name='aed')),
                ('eur', models.IntegerField(help_text='aed', max_length=10, null=None, verbose_name='aed')),
                ('push', models.IntegerField(help_text='aed', max_length=10, null=None, verbose_name='aed')),
            ],
        ),
    ]
