# Generated by Django 4.1.5 on 2023-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0004_alter_users_aed_alter_users_eur_alter_users_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.IntegerField(help_text='usd', max_length=10, null=68, verbose_name='USD')),
                ('aed', models.IntegerField(help_text='aed', max_length=10, null=18, verbose_name='USD')),
                ('eur', models.IntegerField(help_text='aed', max_length=10, null=74, verbose_name='USD')),
            ],
        ),
    ]
