# Generated by Django 4.1.5 on 2023-01-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0009_rates_delete_exchange_rates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rates',
        ),
    ]
